name: test
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build estimator
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.estimator
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Build tester
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.tester
          load: true
          tags: ghcr.io/opencv/bpc/estimator-tester:latest
      -
        name: Build ibpc_py
        run: |
          cd ibpc_py
          python -m pip install -e .
      -
        name: Run bpc fetch
        run: | 
          bpc fetch ipd
# TODO make a bpc test return on success
#      -
#        name: Run bpc test
#        run: | 
#          bpc fetch ipd



